kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: agent-ui
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'agent-ui:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: "https://github.com/IBM/ibmi-mcp-server.git"
      ref: main
    contextDir: agents/docker/ibmi-agent-infra/agent-ui
  triggers:
    - type: ConfigChange


