apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent-ui-buildconfig.yaml
  - agent-ui-imagestream.yaml
  - agent-ui-deployment.yaml
  - agent-ui-service.yaml
  - agent-ui-route.yaml


