apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test

sortOptions:
  legacySortOptions:
    orderFirst:
    - ServiceAccount
    - RoleBinding
    - ConfigMap
    - Secret
    - ImageStream
    - BuildConfig
    - PersistentVolumeClaim
    - Deployment
    - Service
    - Route
  order: legacy

resources:
# - mcpgateway
# - ibmi-mcp-server
- ibmi-agent-infra